from datetime import datetime, timedelta
from app.db.session import SessionLocal
from app.models.user import User, Pet, MedicalRecord, Appointment
from app.models.reports import Report
from app.models.community_posts import CommunityPost
from app.models.sicknesses import Sickness
from app.models.care_team import CareTeamMember
import uuid


def generate_id():
    return str(uuid.uuid4())


def seed_data() -> None:
    db = SessionLocal()
    try:
        # Check if data already exists
        if db.query(User).first():
            return

        # ==================== USERS ====================
        users = [
            User(
                id=generate_id(),
                email="alice@example.com",
                password="hashed_password",
                first_name="Alice",
                last_name="Johnson",
                username="alice_loves_dogs",
                phone="+1-555-0101",
                address="123 Oak Street",
                city="Portland",
                state="OR",
                zip_code="97201",
                country="USA",
                bio="Dog lover and pet care enthusiast. Have two golden retrievers.",
                is_active=True,
                is_verified=True,
                is_veterinarian=False,
                is_pet_caregiver=True,
                followers_count=125,
                following_count=87,
                posts_count=23,
            ),
            User(
                id=generate_id(),
                email="dr_smith@vetclinic.com",
                password="hashed_password",
                first_name="Dr. Michael",
                last_name="Smith",
                username="dr_smith_dvm",
                phone="+1-555-0102",
                address="456 Elm Avenue",
                city="Portland",
                state="OR",
                zip_code="97202",
                country="USA",
                bio="Licensed veterinarian with 15 years of experience. Emergency care specialist.",
                is_active=True,
                is_verified=True,
                is_veterinarian=True,
                professional_license="DVM-OR-2008-12345",
                experience_years=15,
                specializations="Emergency medicine, surgery, internal medicine",
                followers_count=456,
                following_count=34,
                posts_count=67,
            ),
            User(
                id=generate_id(),
                email="groom_paradise@email.com",
                password="hashed_password",
                first_name="Sarah",
                last_name="Williams",
                username="groom_paradise",
                phone="+1-555-0103",
                address="789 Pine Road",
                city="Portland",
                state="OR",
                zip_code="97203",
                country="USA",
                bio="Professional pet groomer. Certified in advanced grooming techniques.",
                is_active=True,
                is_verified=True,
                is_pet_caregiver=True,
                experience_years=8,
                specializations="Dog grooming, cat bathing, nail care",
                followers_count=234,
                following_count=56,
                posts_count=89,
            ),
            User(
                id=generate_id(),
                email="bob@example.com",
                password="hashed_password",
                first_name="Bob",
                last_name="Martinez",
                username="cat_dad_bob",
                phone="+1-555-0104",
                address="321 Maple Lane",
                city="Portland",
                state="OR",
                zip_code="97204",
                country="USA",
                bio="Cat enthusiast. Looking for advice on kitten care and behavior.",
                is_active=True,
                is_verified=False,
                is_pet_caregiver=False,
                followers_count=45,
                following_count=123,
                posts_count=5,
            ),
        ]
        db.add_all(users)
        db.commit()

        # ==================== PETS ====================
        pets = [
            Pet(
                id=generate_id(),
                owner_id=users[0].id,
                name="Max",
                species="Dog",
                breed="Golden Retriever",
                age=36,  # 3 years
                weight="32 kg",
                color="Golden",
                microchip_id="Golden-12345-67890",
                vaccinated=True,
                neutered_spayed=True,
                blood_type="DEA 1.1 positive",
                bio="Friendly and energetic. Loves fetch and swimming.",
                is_active=True,
            ),
            Pet(
                id=generate_id(),
                owner_id=users[0].id,
                name="Bella",
                species="Dog",
                breed="Golden Retriever",
                age=24,  # 2 years
                weight="28 kg",
                color="Light Golden",
                microchip_id="Golden-98765-43210",
                vaccinated=True,
                neutered_spayed=True,
                blood_type="DEA 1.1 positive",
                bio="Gentle and calm. Great with kids.",
                is_active=True,
            ),
            Pet(
                id=generate_id(),
                owner_id=users[3].id,
                name="Whiskers",
                species="Cat",
                breed="Persian",
                age=48,  # 4 years
                weight="4.5 kg",
                color="White",
                microchip_id="Cat-11111-22222",
                vaccinated=True,
                neutered_spayed=True,
                blood_type="Type B",
                bio="Shy but affectionate. Enjoys quiet environments.",
                is_active=True,
            ),
        ]
        db.add_all(pets)
        db.commit()

        # ==================== MEDICAL RECORDS ====================
        medical_records = [
            MedicalRecord(
                id=generate_id(),
                pet_id=pets[0].id,
                record_type="vaccination",
                description="Annual rabies and DHPP vaccination",
                veterinarian="Dr. Michael Smith",
                clinic_name="Portland Veterinary Clinic",
                medications="Nobivac DHPP, Nobivac Rabies",
                record_date=datetime.now() - timedelta(days=30),
            ),
            MedicalRecord(
                id=generate_id(),
                pet_id=pets[0].id,
                record_type="checkup",
                description="Annual wellness exam. All vitals normal.",
                veterinarian="Dr. Michael Smith",
                clinic_name="Portland Veterinary Clinic",
                medications=None,
                record_date=datetime.now() - timedelta(days=25),
            ),
            MedicalRecord(
                id=generate_id(),
                pet_id=pets[2].id,
                record_type="vaccination",
                description="FVRCP vaccination update",
                veterinarian="Dr. Emily Johnson",
                clinic_name="Eastside Pet Hospital",
                medications="FVRCP vaccine",
                record_date=datetime.now() - timedelta(days=60),
            ),
        ]
        db.add_all(medical_records)
        db.commit()

        # ==================== APPOINTMENTS ====================
        appointments = [
            Appointment(
                id=generate_id(),
                pet_id=pets[0].id,
                title="Dental Cleaning",
                description="Professional dental cleaning and check for cavities",
                appointment_type="vet",
                status="scheduled",
                appointment_date=datetime.now() + timedelta(days=14),
                duration_minutes=60,
                provider_name="Dr. Michael Smith",
                provider_phone="+1-555-0102",
                location="Portland Veterinary Clinic",
                notes="Bring vaccination records",
            ),
            Appointment(
                id=generate_id(),
                pet_id=pets[1].id,
                title="Grooming Session",
                description="Full body grooming with nail trim",
                appointment_type="grooming",
                status="scheduled",
                appointment_date=datetime.now() + timedelta(days=7),
                duration_minutes=120,
                provider_name="Sarah Williams",
                provider_phone="+1-555-0103",
                location="Groom Paradise Salon",
                notes="Request hypoallergenic shampoo",
            ),
        ]
        db.add_all(appointments)
        db.commit()

        # ==================== SICKNESSES ====================
        sicknesses = [
            Sickness(
                id=generate_id(),
                name="Canine Parvovirus",
                species="Dog",
                summary="Highly contagious viral disease affecting the GI tract and heart",
                description="Canine parvovirus is a serious and potentially deadly disease in dogs. It spreads through direct contact with contaminated feces.",
                symptoms="Severe vomiting, bloody diarrhea, lethargy, loss of appetite, fever, abdominal pain, dehydration",
                remedies="Immediate veterinary hospitalization, IV fluid therapy, antiemetics, antibiotics, nutritional support, isolation from other dogs",
                prevention="Vaccination with DHPP vaccine, proper sanitation, avoiding contaminated areas",
                severity="critical",
                category="infectious",
                contagious=True,
                causes="Canine parvovirus type 1 and 2",
                incubation_period="3-10 days",
                transmission_methods="Fecal-oral route, contaminated surfaces, direct contact",
                affected_age_group="Puppies (6 weeks - 6 months), unvaccinated dogs",
                typical_treatment_duration="7-14 days hospitalization",
                requires_veterinary_care=True,
                prognosis="Recovery possible with aggressive treatment in young healthy dogs, mortality rate 80% without treatment",
                is_verified=True,
                verified_by="Dr. Michael Smith, DVM",
            ),
            Sickness(
                id=generate_id(),
                name="Feline Upper Respiratory Infection",
                species="Cat",
                summary="Common viral respiratory condition in cats, similar to human cold",
                description="Upper respiratory infections are common in cats, especially in multi-cat households. Often caused by herpesvirus or calicivirus.",
                symptoms="Sneezing, nasal congestion, watery eyes, coughing, sore throat, fever, lethargy",
                remedies="Supportive care including fluid therapy, antihistamines for congestion, warm humid environment, nutritional support, L-lysine supplementation",
                prevention="Vaccination with FVRCP vaccine, maintaining clean litter boxes, reducing stress, isolation of infected cats",
                severity="moderate",
                category="infectious",
                contagious=True,
                causes="Feline herpesvirus 1, feline calicivirus, secondary bacterial infections",
                incubation_period="2-10 days",
                transmission_methods="Airborne droplets, direct contact, contaminated objects",
                affected_age_group="Kittens, elderly cats, immunocompromised cats",
                typical_treatment_duration="7-10 days",
                requires_veterinary_care=True,
                prognosis="Generally good with supportive care, most cats recover fully",
                is_verified=True,
                verified_by="Dr. Emily Johnson, DVM",
            ),
            Sickness(
                id=generate_id(),
                name="Hip Dysplasia in Dogs",
                species="Dog",
                summary="Genetic developmental disorder affecting hip joint formation",
                description="Hip dysplasia is an inherited condition where the femoral head doesn't fit properly into the hip socket, leading to arthritis.",
                symptoms="Limping, reluctance to exercise, difficulty climbing stairs, stiffness after rest, swollen hips, behavioral changes",
                remedies="Weight management, exercise restriction, NSAIDs, physical therapy, CBD supplements, arthritis medication, surgery in severe cases",
                prevention="Responsible breeding, maintaining healthy weight, appropriate exercise, joint supplements from puppyhood",
                severity="moderate",
                category="genetic",
                contagious=False,
                causes="Genetic susceptibility, rapid growth, diet high in calcium/phosphorus",
                incubation_period="Usually manifests between 4-12 months of age",
                transmission_methods="Not contagious, inherited genetic predisposition",
                affected_age_group="Predominantly large breed puppies and young adults",
                typical_treatment_duration="Lifelong management",
                requires_veterinary_care=True,
                prognosis="Can be managed to maintain quality of life, severity varies from mild to severely debilitating",
                is_verified=True,
                verified_by="Dr. Michael Smith, DVM",
            ),
            Sickness(
                id=generate_id(),
                name="Feline Diabetes Mellitus",
                species="Cat",
                summary="Metabolic disease affecting insulin production and glucose regulation",
                description="Feline diabetes is increasingly common in domestic cats. Obesity, age, and genetic factors increase risk.",
                symptoms="Increased thirst and urination, weight loss despite increased appetite, lethargy, strong ammonia odor in urine",
                remedies="Insulin therapy, dietary management with low-carb diet, weight loss, home blood glucose monitoring, regular vet follow-ups",
                prevention="Maintaining healthy weight, appropriate diet rich in protein, stress reduction, regular exercise",
                severity="high",
                category="metabolic",
                contagious=False,
                causes="Pancreatic dysfunction, insulin resistance, obesity, chronic illness",
                incubation_period="Develops gradually over time",
                transmission_methods="Not contagious, genetic predisposition",
                affected_age_group="Older overweight cats (>10 years typical)",
                typical_treatment_duration="Lifelong management",
                requires_veterinary_care=True,
                prognosis="Manageable with proper insulin therapy and diet, some cats go into remission",
                is_verified=True,
                verified_by="Dr. Emily Johnson, DVM",
            ),
        ]
        db.add_all(sicknesses)
        db.commit()

        # ==================== REPORTS ====================
        reports = [
            Report(
                id=generate_id(),
                title="Lost Golden Retriever - Downtown Area",
                description="Missing since Tuesday morning. Very friendly, wearing a blue collar with ID tag. Responds to name Max. Please call if spotted.",
                location="Downtown Portland",
                latitude=45.5152,
                longitude=-122.6784,
                category="Lost",
                status="open",
                species="Dog",
                breed="Golden Retriever",
                urgency="high",
                reporter_name="Alice Johnson",
                reporter_email="alice@example.com",
                reporter_phone="+1-555-0101",
                pet_name="Max",
                pet_color="Golden",
                is_verified=True,
                view_count=156,
                comment_count=12,
                reaction_count=34,
                created_at=datetime.now() - timedelta(days=2),
            ),
            Report(
                id=generate_id(),
                title="Found Orange Kitten Near McKenzie Park",
                description="Found a small orange kitten about 2 months old. Very playful and hungry. Currently caring for it temporarily. Please contact if it's yours.",
                location="McKenzie Park",
                latitude=45.5236,
                longitude=-122.7033,
                category="Found",
                status="open",
                species="Cat",
                urgency="medium",
                reporter_name="Bob Martinez",
                reporter_email="bob@example.com",
                reporter_phone="+1-555-0104",
                pet_color="Orange tabby",
                is_verified=False,
                view_count=89,
                comment_count=7,
                reaction_count=18,
                created_at=datetime.now() - timedelta(days=1),
            ),
            Report(
                id=generate_id(),
                title="Dog Behavior Training Group Starting",
                description="Forming a dog training group to work on leash manners and basic obedience. Meet every Saturday at Washington Park. All skill levels welcome!",
                location="Washington Park",
                latitude=45.5040,
                longitude=-122.7220,
                category="Care",
                status="open",
                species="Dog",
                urgency="low",
                reporter_name="Sarah Williams",
                reporter_email="groom_paradise@email.com",
                reporter_phone="+1-555-0103",
                is_verified=True,
                view_count=234,
                comment_count=23,
                reaction_count=67,
                created_at=datetime.now() - timedelta(hours=6),
            ),
            Report(
                id=generate_id(),
                title="Rabies Alert - Raccoon Spotted in Residential Area",
                description="Wildlife control has reported raccoon activity in the Laurelhurst neighborhood. Unusual daytime behavior reported. Keep pets vaccinated and away from wildlife.",
                location="Laurelhurst, Portland",
                latitude=45.5146,
                longitude=-122.6267,
                category="Health",
                status="monitoring",
                species="Other",
                urgency="high",
                reporter_name="Dr. Michael Smith",
                reporter_email="dr_smith@vetclinic.com",
                reporter_phone="+1-555-0102",
                is_verified=True,
                view_count=412,
                comment_count=34,
                reaction_count=89,
                created_at=datetime.now() - timedelta(hours=12),
            ),
        ]
        db.add_all(reports)
        db.commit()

        # ==================== COMMUNITY POSTS ====================
        community_posts = [
            CommunityPost(
                id=generate_id(),
                title="Best Tips for Introducing Cats to a New Home",
                body="Just moved to Portland with my two cats! Here are the tips that helped them adjust quickly:\n\n1. Set up a safe room first with all essentials\n2. Let them explore gradually\n3. Use familiar bedding and toys\n4. Keep routines consistent\n5. Be patient - adjustment takes time\n\nWhat worked for your cats?",
                category="tips",
                author_id=users[3].id,
                author_name="Bob Martinez",
                is_pinned=False,
                is_verified=False,
                status="published",
                tags="cat, moving, introduction, tips",
                view_count=324,
                comment_count=18,
                reaction_count=89,
                created_at=datetime.now() - timedelta(days=3),
            ),
            CommunityPost(
                id=generate_id(),
                title="Success Story: Max's Journey to Recovery",
                body="After 2 years of wondering about proper nutrition, Max finally has his energy back! Working with Dr. Smith and Sarah for grooming was the key.\n\nIf your dog seems lethargic, could be worth checking diet and overall health with a vet visit. 🐕‍🦺",
                category="stories",
                author_id=users[0].id,
                author_name="Alice Johnson",
                is_pinned=True,
                is_verified=True,
                status="published",
                tags="dog, health, nutrition, success",
                featured=True,
                featured_at=datetime.now() - timedelta(hours=3),
                view_count=891,
                comment_count=45,
                reaction_count=234,
                created_at=datetime.now() - timedelta(days=1),
            ),
            CommunityPost(
                id=generate_id(),
                title="Q: What's your favorite pet-friendly cafe in Portland?",
                body="Looking for recommendations for coffee shops where I can bring Max and Bella! We want to enjoy the nice weather together.\n\nAnyone have favorites? 😊",
                category="questions",
                author_id=users[0].id,
                author_name="Alice Johnson",
                is_pinned=False,
                is_verified=False,
                status="published",
                tags="portland, cafe, dogs, social",
                view_count=567,
                comment_count=32,
                reaction_count=78,
                created_at=datetime.now() - timedelta(hours=18),
            ),
            CommunityPost(
                id=generate_id(),
                title="Professional Grooming Special - Limited Time!",
                body="At Groom Paradise, we're offering 20% off for first-time customers! Full body grooming includes:\n✨ Bath and dry\n✨ Nail trimming\n✨ Ear cleaning\n✨ Teeth brushing\n\nBook your appointment today! Limited spots available.",
                category="announcements",
                author_id=users[2].id,
                author_name="Sarah Williams",
                is_pinned=True,
                is_verified=True,
                status="published",
                tags="grooming, special, professional, service",
                view_count=1203,
                comment_count=67,
                reaction_count=156,
                created_at=datetime.now() - timedelta(hours=2),
            ),
        ]
        db.add_all(community_posts)
        db.commit()

        print("✅ Database seeded successfully with realistic pet care data!")

    except Exception as e:
        db.rollback()
        print(f"❌ Error seeding database: {e}")
    finally:
        db.close()
